[Variables]

Location=GRXX0004
Unit=m
ScrollMouseIncrement=0.05
Format=H
Hidden=0
Hidden2=1
Color1=255,255,255
Color2=129,161,193
Color3=180,142,173
Color4=163,190,140
Color5=191,97,106
Color6=240,148,0
UserName=Connect-R


;NOTES:

;This below is the settings for the dock with icons.
;If you are not familiar with Rainmeter from earlier,please don't edit anything!
;It's too complicated and sensitive,if you don't know what you doing!
;But i will try to explain to you as much as i can.This "#@#\" is shortened for "@Resources" folder.It's a folder where the icons and other parts of the skin are located.
;If you want to change icon-s,with new icon-s,you must put it in "@Resources" folder. Also, icons must be in PNG file format.
;When you change "icon and name path",for example if you want to change "My Computer" icon to "CCleaner",it should look like this:

;This is example for some program:

;
;Name1=CCleaner
;TextName1=CCleaner
;LocationPath1=["C:\Program Files\CCleaner\CCleaner64.exe"]

;This is example for some internet links:

;Name2=Twitter
;TextName2=Twitter
;LocationPath2=["https://twitter.com/?lang=en"]

;etc..

;----------------------Icon Dock Settings--------------------------
;------------------------------------------------------------------

Icon1NameAndPath=#@#\Internet.png
TextName1=Internet
LocationPath1=["https://www.google.com"]

Icon2NameAndPath=#@#\Music.png
TextName2=Music
LocationPath2=[Shell:::{1CF1260C-4DD0-4ebb-811F-33C572699FDE}]

Icon3NameAndPath=#@#\Picture.png
TextName3=Pictures
LocationPath3=[Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]

Icon4NameAndPath=#@#\Video.png
TextName4=Video
LocationPath4=[Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}]

Icon5NameAndPath=#@#\Facebook.png
TextName5=Facebook
LocationPath5=["https://facebook.com/"]

Icon6NameAndPath=#@#\Email.png
TextName6=Email
LocationPath6=["https://mail.google.com/mail/"]


